# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\".\n\x08UserData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"h\n\x0eUserDataUpdate\x12\x14\n\x0cold_username\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_username\x18\x03 \x01(\t\x12\x14\n\x0cnew_password\x18\x04 \x01(\t\"0\n\x0cUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xac\x01\n\x0bUserService\x12#\n\x05login\x12\t.UserData\x1a\r.UserResponse\"\x00\x12&\n\x08register\x12\t.UserData\x1a\r.UserResponse\"\x00\x12$\n\x06\x64\x65lete\x12\t.UserData\x1a\r.UserResponse\"\x00\x12*\n\x06update\x12\x0f.UserDataUpdate\x1a\r.UserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERDATA._serialized_start=15
  _USERDATA._serialized_end=61
  _USERDATAUPDATE._serialized_start=63
  _USERDATAUPDATE._serialized_end=167
  _USERRESPONSE._serialized_start=169
  _USERRESPONSE._serialized_end=217
  _USERSERVICE._serialized_start=220
  _USERSERVICE._serialized_end=392
# @@protoc_insertion_point(module_scope)
